const fs = require('fs');

const rawData = JSON.parse(fs.readFileSync('real_data.json', 'utf8'));

let sql = `-- ========================================================
-- REAL SEED DATA (MIGRATED FROM EXCEL & AUTOGENERATED SMP DATA)
-- ========================================================

-- Disable constraints temporarily to safely insert
SET FOREIGN_KEY_CHECKS = 0;

`;

let usersQuery = [];
let classesQuery = [];
let teachersQuery = [];
let studentsQuery = [];
let subjectsQuery = [];
let schedulesQuery = [];

let userIdCounter = 20;
let classIdCounter = 100;
let teacherIdCounter = 50;
let studentIdCounter = 1000;

// Mapping to link teachers
const teacherMap = {}; // name -> { uid, tid }
const classMap = {}; // name -> classId

// ============================================
// A. MAPEL & GURU MAPEL (SMP)
// ============================================
const subjectsData = [
  { id: 101, name: 'Matematika', code: 'MATH-SMP', teacherName: 'Pak Anwar (Matematika)' },
  { id: 102, name: 'Bahasa Indonesia', code: 'INDO-SMP', teacherName: 'Ibu Ningsih (B.Indo)' },
  { id: 103, name: 'Bahasa Inggris', code: 'ENGL-SMP', teacherName: 'Mr. John (B.Inggris)' },
  { id: 104, name: 'Ilmu Pengetahuan Alam (IPA)', code: 'IPA-SMP', teacherName: 'Ibu Kartika (IPA)' },
  { id: 105, name: 'Ilmu Pengetahuan Sosial (IPS)', code: 'IPS-SMP', teacherName: 'Pak Budi (IPS)' },
  { id: 106, name: 'Pend. Pancasila dan Kewarganegaraan (PPKn)', code: 'PPKN-SMP', teacherName: 'Pak Susilo (PPKn)' },
  { id: 107, name: 'Pendidikan Agama Islam (PAI)', code: 'PAI-SMP', teacherName: 'Ustadz Ahmad (PAI)' }
];

subjectsData.forEach(sub => {
    // Insert Subject
    subjectsQuery.push(`(${sub.id}, '${sub.name}', '${sub.code}')`);

    // Insert Subject Teacher User & Teacher profile
    const uid = userIdCounter++;
    const tid = teacherIdCounter++;
    const email = `guru.mapel${sub.id}@guru.educore.id`;
    
    usersQuery.push(`(${uid}, '${email}', 'password', 'guru_mapel', '${sub.teacherName}', 'active')`);
    teachersQuery.push(`(${tid}, ${uid}, 'NIP${uid}', ${sub.id})`); // specialty_subject_id = sub.id
    
    // Store tid in sub object for scheduling
    sub.tid = tid;
});

// ============================================
// B. WALI KELAS
// ============================================
for (const className in rawData) {
    const classData = rawData[className];
    const waliName = classData.wali_kelas || `Wali ${className}`;
    
    if (!teacherMap[waliName]) {
        const uid = userIdCounter++;
        const tid = teacherIdCounter++;
        const email = waliName.toLowerCase().replace(/[^a-z0-9]/g, '').substring(0, 10) + uid + '@guru.educore.id';
        
        usersQuery.push(`(${uid}, '${email}', 'password', 'wali_kelas', '${waliName}', 'active')`);
        teachersQuery.push(`(${tid}, ${uid}, 'NIP${uid}', NULL)`);
        
        teacherMap[waliName] = { uid, tid };
    }
}

// ============================================
// C. KELAS & JADWAL
// ============================================
const days = ['Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat'];
const timeSlots = [
  { start: '07:30:00', end: '09:00:00' },
  { start: '09:15:00', end: '10:45:00' },
  { start: '11:00:00', end: '12:30:00' }
];

for (const className in rawData) {
    const classData = rawData[className];
    const waliName = classData.wali_kelas || `Wali ${className}`;
    const waliTeacherId = teacherMap[waliName].tid;
    
    const cid = classIdCounter++;
    const gradeLevel = className.includes('VII') ? 7 : className.includes('VIII') ? 8 : 9;
    classesQuery.push(`(${cid}, '${className}', ${gradeLevel}, 'Ruang ${className}', ${waliTeacherId})`);
    classMap[className] = cid;

    // Generate Schedules for this class (Randomize order of subjects slightly for each class)
    // Create a copy of subjects and shuffle them basically to spread across 5 days
    let classSubjects = [...subjectsData];
    // Simple determinisic shift based on cid so classes have different schedules
    for(let i=0; i < (cid % 7); i++) {
        classSubjects.push(classSubjects.shift());
    }

    let subjIdx = 0;
    for (let dayIdx = 0; dayIdx < days.length; dayIdx++) {
        // Each day gets 1 or 2 subjects
        let subjectsPerDay = (dayIdx === 4) ? 1 : 2; // Jumat only 1, others 2 (total = 1+8=9, we only have 7 mapel)
        // Wait, 7 mapel across 5 days. Let's just assign all 7 linearly across available slots.
    }
    
    // Assign linearly
    let slotCount = 0;
    for(let s = 0; s < 7; s++) {
        const sub = classSubjects[s];
        const day = days[Math.floor(slotCount / 2)]; // 2 subjects per day max
        const time = timeSlots[slotCount % 2];
        schedulesQuery.push(`(${cid}, ${sub.id}, ${sub.tid}, '${day}', '${time.start}', '${time.end}')`);
        slotCount++;
    }
}

// ============================================
// D. SISWA
// ============================================
for (const className in rawData) {
    const classData = rawData[className];
    const cid = classMap[className];
    
    for (const student of classData.students) {
        const uid = userIdCounter++;
        let email = student.nisn ? `${student.nisn}@siswa.educore.id` : `siswa${uid}@siswa.educore.id`;
        
        usersQuery.push(`(${uid}, '${email}', 'password', 'siswa', '${student.name.replace(/'/g, "''")}', 'active')`);
        studentsQuery.push(`(${studentIdCounter++}, ${uid}, '${student.nisn || student.nis || 'NIS'+uid}', ${cid})`);
    }
}

// ============================================
// E. CONSTRUCT FINAL SQL
// ============================================
sql += `INSERT INTO \`users\` (\`id\`, \`email\`, \`password\`, \`role\`, \`name\`, \`status\`) VALUES\n`;
sql += usersQuery.join(',\n') + '\nON DUPLICATE KEY UPDATE `email` = VALUES(`email`), `name` = VALUES(`name`);\n\n';

sql += `INSERT INTO \`subjects\` (\`id\`, \`name\`, \`code\`) VALUES\n`;
sql += subjectsQuery.join(',\n') + '\nON DUPLICATE KEY UPDATE `name` = VALUES(`name`);\n\n';

sql += `INSERT INTO \`teachers\` (\`id\`, \`user_id\`, \`nip\`, \`specialty_subject_id\`) VALUES\n`;
sql += teachersQuery.join(',\n') + '\nON DUPLICATE KEY UPDATE `nip` = VALUES(`nip`);\n\n';

sql += `INSERT INTO \`classes\` (\`id\`, \`name\`, \`grade_level\`, \`room_name\`, \`homeroom_teacher_id\`) VALUES\n`;
sql += classesQuery.join(',\n') + '\nON DUPLICATE KEY UPDATE `name` = VALUES(`name`);\n\n';

sql += `INSERT INTO \`students\` (\`id\`, \`user_id\`, \`nisn\`, \`class_id\`) VALUES\n`;
sql += studentsQuery.join(',\n') + '\nON DUPLICATE KEY UPDATE `nisn` = VALUES(`nisn`);\n\n';

sql += `INSERT INTO \`schedules\` (\`class_id\`, \`subject_id\`, \`teacher_id\`, \`day\`, \`start_time\`, \`end_time\`) VALUES\n`;
sql += schedulesQuery.join(',\n') + ';\n\n';

sql += '-- Re-enable constraints\nSET FOREIGN_KEY_CHECKS = 1;\n';

fs.writeFileSync('seed-real.sql', sql);
console.log('Successfully generated seed-real.sql with 7 SMP subjects and schedules!');
